export const ADD_COUNTRY_REJECTED = 'ADD_COUNTRY_REJECTED';
export const ADD_COUNTRY_STARTED = 'ADD_COUNTRY_STARTED';
export const ADD_COUNTRY_SUCCESS = 'ADD_COUNTRY_SUCCESS';

export const ADD_COUNTRY_REJECTE = 'ADD_COUNTRY_REJECTED';
export const ADD_COUNTRY_STARTE = 'ADD_COUNTRY_STARTED';
export const ADD_COUNTRY_SUCCES = 'ADD_COUNTRY_SUCCESS';